// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.Entities;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230620132651_mod_holidayTBL_add_isDisabled")]
    partial class mod_holidayTBL_add_isDisabled
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("webapi.Entities.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOff")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description4")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description5")
                        .HasColumnType("TEXT");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgCaption1")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgCaption2")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgCaption3")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgCaption4")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgCaption5")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgUrl1")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgUrl2")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgUrl3")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgUrl4")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgUrl5")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsImportant")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLunarHoliday")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferenceLinks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Holidays");
                });
#pragma warning restore 612, 618
        }
    }
}
